apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  labels:
    app: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /actuator/prometheus
        prometheus.io/port: "9002"
    spec:
      containers:
        - name: order-service
          image: ghcr.io/rajanjha786/order-service
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                # Send the SIGTERM signal to pod after 5 seconds after informing all the components to not send the request to this pod
                command: ["sh", "-c", "sleep 5"]
          ports:
            - containerPort: 9002
          env:
            - name: BPL_JVM_THREAD_COUNT
              value: "50"
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://bookshop-postgres/bookshop_order
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://config-service
            - name: BOOKSHOP_CATALOG_SERVICE_URI
              value: http://catalog-service
            - name: SPRING_R2DBC_URL
              value: r2dbc:postgresql://bookshop-postgres:5432/bookshop_order
            - name: SPRING_FLYWAY_URL
              value: jdbc:postgresql://bookshop-postgres:5432/bookshop_order
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 9002
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 9002
            initialDelaySeconds: 5
            periodSeconds: 15
