apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  labels:
    app: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: ghcr.io/rajanjha786/order-service
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                # Send the SIGTERM signal to pod after 5 seconds after informing all the components to not send the request to this pod
                command: ["sh", "-c", "sleep 5"]
          ports:
            - containerPort: 8000
          env:
            - name: BPL_JVM_THREAD_COUNT
              value: "50"
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://bookshop-postgres/bookshop_order
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://config-service
            - name: BOOKSHOP_CATALOG_SERVICE_URI
              value: http://catalog-service
